#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# 🔧 load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm use default --silent

echo "🔧 linting..."
pnpm run lint-staged:husky

echo "📦 build..."
pnpm run build

echo "🧪 fast tests..."
pnpm run test:husky